// <auto-generated />
using Bakery.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bakery.Data.Migrations
{
    [DbContext(typeof(BakeryContext))]
    [Migration("20200506084927_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Bakery.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .HasColumnName("ImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Beschte Döner wo gibt",
                            ImageName = "doener.jpg",
                            Name = "Döner Tasche",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ein kleiner Snack für zwischendurch",
                            ImageName = "burger.png",
                            Name = "Burger",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Die schöne alternative zur Pizza",
                            ImageName = "pide.jpg",
                            Name = "Pide",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lamm auf die beste Art und Weise",
                            ImageName = "kuzu.jpg",
                            Name = "Kuzu Pirzola",
                            Price = 1.49m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Baklava geht immer",
                            ImageName = "baklava.jpg",
                            Name = "Baklava",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Wer es bis jetzt noch nicht probiert, dann wirds mal Zeit",
                            ImageName = "kunefa.jpg",
                            Name = "Künefe",
                            Price = 8.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
